variable "proxmox_url" {
  type        = string
  description = "Proxmox API URL, e.g. https://proxmox.example.internal:8006/api2/json"
  # Placeholder, not real — packer validate requires this non-empty, and
  # there's no host to point it at yet regardless. Matches example.pkrvars.hcl.
  default = "https://proxmox.example.internal:8006/api2/json"
}

variable "proxmox_node" {
  type        = string
  description = "Proxmox node name the templates are built on"
  default     = "pve" # placeholder — same reasoning as proxmox_url above.
}

variable "proxmox_api_token_id" {
  type        = string
  description = "Proxmox API token ID, e.g. root@pam!packer"
  default     = "root@pam!packer" # placeholder — same reasoning as proxmox_url above.
}

variable "proxmox_api_token_secret" {
  type        = string
  description = "Proxmox API token secret"
  # "REPLACE_ME", not empty — same reasoning as proxmox_url above. Not a real
  # secret; sensitive = true is what actually matters here.
  default   = "REPLACE_ME"
  sensitive = true
}

variable "proxmox_bridge_build" {
  type        = string
  description = "Internal, disposable Proxmox bridge every build VM attaches to — no VLAN, no production traffic, DHCP served by the host-side runner's dnsmasq. See the host-network SPIKE in PLAN.md; not vmbr0 (WAN) or vmbr1 (the VLAN trunk), which is why this is its own variable rather than terraform/'s proxmox_bridge_wan/_trunk reused."
  default     = "vmbr2"
}

variable "iso_datastore" {
  type        = string
  description = "Datastore that holds installation and VirtIO ISOs"
  default     = "local"
}

variable "template_datastore" {
  type        = string
  description = "Datastore for template disks, the EFI disk and TPM state"
  default     = "local-lvm"
}

variable "win_server_iso_url" {
  type        = string
  description = "URL Proxmox downloads the German Windows Server 2025 ISO from (iso_download_pve) — its filename must match the Packer templates table in docs/conventions.md exactly, since that filename becomes the datastore path"
  default     = "https://example.invalid/win-server-2025-de.iso"
}

variable "win_server_iso_checksum" {
  type        = string
  description = "sha256:<hash> for win_server_iso_url — \"none\" until the real ISO is checksummed"
  default     = "none"
}

variable "win11_iso_url" {
  type        = string
  description = "URL Proxmox downloads the German Windows 11 Pro ISO from (iso_download_pve) — see win_server_iso_url on why the filename matters"
  default     = "https://example.invalid/win-11-pro-de.iso"
}

variable "win11_iso_checksum" {
  type        = string
  description = "sha256:<hash> for win11_iso_url — \"none\" until the real ISO is checksummed"
  default     = "none"
}

variable "virtio_iso_url" {
  type        = string
  description = "URL Proxmox downloads the version-pinned VirtIO driver ISO from (iso_download_pve) — no \"latest\" alias, per docs/conventions.md; see win_server_iso_url on why the filename matters"
  default     = "https://example.invalid/virtio-win-0.1.285.iso"
}

variable "virtio_iso_checksum" {
  type        = string
  description = "sha256:<hash> for virtio_iso_url — \"none\" until the real ISO is checksummed"
  default     = "none"
}

variable "local_admin_password" {
  type        = string
  description = "Local administrator password baked into both answer files"
  default     = ""
  sensitive   = true
}

variable "opnsense_iso_file" {
  type        = string
  description = "ISO filename on iso_datastore — see the Packer templates table in docs/conventions.md. Placed there by the host-runner's download step (opnsense_iso_url below), not by this file's own boot_iso block — OPNsense ships compressed, see that variable."
  default     = "OPNsense-26.7-dvd-amd64.iso"
}

variable "opnsense_iso_checksum" {
  type        = string
  description = "sha256:<hash> of the DECOMPRESSED opnsense_iso_file — \"none\" until the real ISO is checksummed. Verified by the host-runner's download step, not by Packer — see opnsense_iso_url."
  default     = "none"
}

variable "opnsense_iso_url" {
  type        = string
  description = "URL of OPNsense's official installer image, shipped as .iso.bz2 — Packer/Proxmox's iso_download_pve cannot decompress it, so the host-side runner downloads and decompresses this into opnsense_iso_file itself, verifying opnsense_iso_checksum by hand. Not read by any .pkr.hcl source; recorded here only so every ISO source lives in one non-secret file (task 5, PLAN.md)."
  default     = "https://example.invalid/OPNsense-26.7-dvd-amd64.iso.bz2"
}

variable "opnsense_api_key" {
  type        = string
  description = "API key baked into config.xml for opnsense/'s Terraform provider — plaintext, never hashed"
  default     = ""
  sensitive   = true
}

variable "opnsense_api_secret_hash" {
  type        = string
  description = "sha512crypt hash of the API secret, generated by scripts/init-env.sh — config.xml never sees the plaintext"
  default     = ""
  sensitive   = true
}

variable "opnsense_root_password" {
  type        = string
  description = "Real root password, rotated in over SSH after install — config.xml itself only ever carries a fixed bootstrap hash, see PLAN.md"
  default     = ""
  sensitive   = true
}
